version: '3.9'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ
    ports:
      - ${PORT}:3306
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql

